version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=example_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=example_db
  app:
    build:
      context: .
      target: prod
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    # volumes:
      # - .:/go/src/app
