// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewUser struct {
	Number *string `json:"number"`
	Name   *string `json:"name"`
	Email  *string `json:"email"`
	Grade  *uint   `json:"grade"`
}
