// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type EditCalender struct {
	Date    time.Time `json:"date"`
	Holiday bool      `json:"holiday"`
}

type EditCast struct {
	ID       uint `json:"id"`
	OptionID uint `json:"optionId"`
}

type EditEvent struct {
	ID      uint      `json:"id"`
	Name    string    `json:"name"`
	Place   string    `json:"place"`
	OwnerID uint      `json:"ownerId"`
	Date    time.Time `json:"date"`
	UsersID []uint    `json:"usersId"`
}

type EditGroup struct {
	GroupID uint   `json:"groupId"`
	Name    string `json:"name"`
}

type EditOption struct {
	ID   uint   `json:"id"`
	Name string `json:"name"`
}

type EditUser struct {
	UserID  uint    `json:"userId"`
	Name    *string `json:"name"`
	Email   *string `json:"email"`
	Grade   *uint   `json:"grade"`
	GroupID *uint   `json:"groupId"`
}

type EditVote struct {
	ID      uint   `json:"id"`
	Name    string `json:"name"`
	EventID uint   `json:"eventId"`
}

type NewCalender struct {
	Date    time.Time `json:"date"`
	Holiday bool      `json:"holiday"`
}

type NewCast struct {
	OptionID uint `json:"optionId"`
	UserID   uint `json:"userId"`
}

type NewEvent struct {
	Name    string    `json:"name"`
	Place   string    `json:"place"`
	OwnerID uint      `json:"ownerId"`
	Date    time.Time `json:"date"`
	UsersID []uint    `json:"usersId"`
}

type NewGroup struct {
	Name string `json:"name"`
}

type NewOption struct {
	Name   string `json:"name"`
	VoteID uint   `json:"voteId"`
}

type NewUser struct {
	Name    string `json:"name"`
	Email   string `json:"email"`
	Grade   uint   `json:"grade"`
	GroupID uint   `json:"groupId"`
}

type NewVote struct {
	Name    string `json:"name"`
	EventID uint   `json:"eventId"`
}
